/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f2eff5',
        'on-tertiary-fixed-variant': '#41474d',
        'secondary-fixed-dim': '#a5caf2',
        'surface-container-lowest': '#ffffff',
        'outline': '#7d7480',
        'background': '#fbf9fd',
        'on-primary-fixed': '#2f004c',
        'on-secondary-container': '#375d7f',
        'tertiary-container': '#5a6066',
        'surface-container-high': '#ece8ef',
        'on-tertiary-container': '#d5dbe2',
        'on-primary-container': '#efcfff',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#161c21',
        'tertiary-fixed': '#dde3ea',
        'on-surface': '#171c21',
        'inverse-primary': '#e3b5ff',
        'on-primary-fixed-variant': '#60327f',
        'primary-container': '#7a4b9a',
        'error-container': '#ffdad6',
        'primary': '#613380',
        'surface-container': '#f2eff5',
        'tertiary-fixed-dim': '#c1c7ce',
        'surface-variant': '#e6e1ea',
        'secondary': '#3c6184',
        'on-surface-variant': '#4c444f',
        'surface-container-low': '#f7f4f9',
        'on-secondary-fixed-variant': '#224a6b',
        'secondary-container': '#b0d5fd',
        'surface-bright': '#fbf9fd',
        'inverse-surface': '#2c3136',
        'primary-fixed': '#f3daff',
        'on-secondary-fixed': '#001d33',
        'on-secondary': '#ffffff',
        'on-background': '#171c21',
        'surface-container-highest': '#e6e1ea',
        'surface': '#fbf9fd',
        'on-primary': '#ffffff',
        'surface-tint': '#794a99',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#e3b5ff',
        'secondary-fixed': '#cee5ff',
        'tertiary': '#42484e',
        'outline-variant': '#cec3d0',
        'surface-dim': '#dcd7e0',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
      },
      // A real scale. The pages previously mixed the configured steps with
      // arbitrary values (1.5rem, 2rem, 2.5rem, 3rem) with no system behind it.
      borderRadius: {
        DEFAULT: '0.625rem',
        'sm': '0.375rem',
        'md': '0.625rem',
        'lg': '0.875rem',
        'xl': '1.25rem',
        '2xl': '1.75rem',
        '3xl': '2.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
